#!/bin/bash

#Создаём общую виртуальную сеть
docker network create --driver bridge strahovka

docker volume create portainer_data

sudo docker run -d -p 8000:8000 -p 9000:9000 --name=portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data --network="strahovka" portainer/portainer-ce